export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const DELETE_ENTIRE_ITEM_FROM_CART = 'DELETE_ENTIRE_ITEM_FROM_CART';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const RESET_CATEOGRY = 'RESET_CATEGORY';